# the name of your lambda function
# this value will be used to lookup up an existing lambda function
name: lambda-text2vec
architecture: arm64
rolename: ie2-lambda-s3readerwriter
runtime: provided.al2023
handler: bootstrap
filename: bootstrap.zip