# for use with AWS CodeBuild
version: 0.2

env:
  shell: /bin/sh
phases:
  install:
    runtime-versions:
      golang: 1.21
    commands:
      - go version
      - go get .
      - chmod +x ./scripts/build.sh
  build:
    commands:
      - ./scripts/build.sh
artifacts:
  files:
    - "**/*"
  base-directory: dist